apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ibkxav6ra-java-springboot
  janus-idp.io/tekton: ibkxav6ra-java-springboot
  backstage.io/kubernetes-id: ibkxav6ra-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ibkxav6ra-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
